export { default as DeleteGenre } from './deleteGenre/deleteGenre';
export { default as DeleteMovie } from './deleteMovie/deleteMovie';
export { default as ErrorTxt} from './error/errorTxt';
export { default as Header } from './header/header';
export { default as Links } from './header/components/links';
export { default as Loader } from './loader/loader';
export { default as MovieBoxBtn } from './button/movieBox.btn';
export { default as HookFormInput } from './react-hook-input/HookFormInput';
export { default as Menu } from './header/components/menu';
export { default as Modal } from './modal/modal';
export { default as Movie } from './movie/movie';
export { default as MovieModal } from './movie/movieModal/movie.modal';
export { default as Order } from './queries/order/order';
export { default as Pagination } from './queries/pagination/pagination';
export { default as Sort } from './queries/sort/sort';
export { default as SubmitError } from './submitError/submitError';